@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Edit election details</div>
                    <div class="card-body">
                        @if (\Session::has('adminStatus'))
                            <div class="alert alert-primary" role="alert">
                                {{ \Session::get('adminStatus') }}
                            </div>
                        @endif
                        <form method="post" action="{{ route('elections.update', ['election' => $election->id]) }}">
                            @csrf
                            @method('patch')
                            <div class="form-group row">
                                <label for="name" class="col-sm-4 col-form-label">Election Name</label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control" id="name" name="plainName" value="{{ $election->plainName }}" required>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="description" class="col-sm-4 col-form-label">Election Description</label>
                                <div class="col-sm-8">
                                    <textarea class="form-control" id="description" name="description">{{ $election->description }}</textarea>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="seats" class="col-sm-4 col-form-label">Seats</label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control" id="seats" name="seats" value="{{ $election->seats }}">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="votingStart" class="col-sm-4 col-form-label">Voting Start</label>
                                <div class="col-sm-8">
                                    <input type="datetime-local" class="form-control" id="votingStart" name="votingStart" value="{{ $election->voting_start->format('Y-m-d\\TH:i') }}" required>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="votingEnd" class="col-sm-4 col-form-label">Voting End</label>
                                <div class="col-sm-8">
                                    <input type="datetime-local" class="form-control" id="votingEnd" name="votingEnd" value="{{ $election->voting_end->format('Y-m-d\\TH:i') }}" required>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary">Update election details</button>
                        </form>
                        <br><a href="/admin/candidates/create?election={{$election->id}}"><h5>Add candidate</h5></a><br>
                        <h5>Edit existing candidates:</h5>
                        @foreach($election->candidates as $candidate)
                            <a href="{{ route('candidates.edit', ['candidate' => $candidate->id]) }}"><h5>{{ $candidate->name }}</h5></a>
                        @endforeach
                        <br>
                        <h5>Export election results</h5>
                                <a href="/admin/export-results/{{$election->id}}"><h5>Download .blt file</h5></a>
                        <p>The file generated by clicking the link above is suitable for use in software such as <a href="https://github.com/Conservatory/openstv">OpenSTV</a> to generate results. It includes details of all withdrawn candidates, candidate names, and all votes for this election in a machine readable format.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
